[%
    T = {
        title = "Checkout report link",
        description = "Link to the checkout statistics report on the record's main page. Add the report number to the 'Configure' section. (Local institution feature)",
        home = "Home",
        plugins = "Plugins",
        configuration = "Configuration",
        back = "Back",
        save = "Save configuration",
        config_label = "Report ID to use:",
        upgrade_status = "Upgrade status",
        last_upgraded = "Plugin was last upgraded on this system on",
        never_upgraded = "Plugin has never been upgraded."
    }
%]