[%
    T = {
        title                                      = "Checkout report link",
        home                                       = "Home",
        plugins                                    = "Plugins",
        configuration                              = "Configuration",
        save                                       = "Save configuration",
        config_label                               = "Report ID:",
        upgrade_status                             = "Upgrade status",
        last_upgraded                              = "Plugin was last upgraded on",
        never_upgraded                             = "Plugin has never been upgraded."
        viewjs_1                                   = "IntranetUserJS: Checkout report link",
        viewjs_4                                   = "&rsaquo; IntranetUserJS: Checkout report link &rsaquo; View JS plugin",
    }
%]