[%
    T = {
        title                                      = "Linkki lainatilastoraporttiin",
        home                                       = "Etusivu",
        plugins                                    = "Liitännäiset",
        configuration                              = "Määritykset",
        save                                       = "Tallenna määritykset",
        config_label                               = "Raportin ID:",
        upgrade_status                             = "Päivityksen tila",
        last_upgraded                              = "Liitännäinen päivitettiin viimeksi",
        never_upgraded                             = "Liitännäistä ei ole koskaan päivitetty."
        viewjs_1                                   = "IntranetUserJS: Linkki lainatilastoraporttiin",
        viewjs_4                                   = "&rsaquo; IntranetUserJS: Linkki lainatilastoraporttiin &rsaquo; Näytä JS-liitännäinen",
    }
%]