[%
    T = {
        title = "Lainatilastoraporttiin linkki",
        description = "Linkki lainatilastoraporttiin tietueen pääsivulla. Lisää Määrittely-osioon käytettävän raportin numero. (Paikalliskannat)",
        home = "Etusivu",
        plugins = "Liitännäiset",
        configuration = "Määritys",
        back = "Takaisin",
        save = "Tallenna määritys",
        config_label = "Käytettävän raportin ID:",
        upgrade_status = "Päivityksen tila",
        last_upgraded = "Liitännäinen päivitettiin viimeksi tähän järjestelmään",
        never_upgraded = "Liitännäistä ei ole koskaan päivitetty."
    }
%]