[%
    T = {
        title                                      = "Länk till utlåningsstatistikrapporten",
        home                                       = "Hem",
        plugins                                    = "Plugins",
        configuration                              = "Inställningar",
        save                                       = "Spara inställningar",
        config_label                               = "Rapport‑ID:",
        upgrade_status                             = "Uppdateringsstatus",
        last_upgraded                              = "Plugin uppdaterats senast",
        never_upgraded                             = "Plugin har aldrig uppdaterats."
        viewjs_1                                   = "IntranetUserJS: Länk till utlåningsstatistikrapporten",
        viewjs_4                                   = "&rsaquo; IntranetUserJS: Länk till utlåningsstatistikrapporten &rsaquo; Visa JS-plugin",
    }
%]