[%
    T = {
        title = "Utlåningsstatistikrapporten länk",
        description = "Länk till utlåningsstatistikrapporten på postens huvudsida. Lägg till rapportnumret som ska användas i avsnittet 'Konfigurera'. (Lokal institutionsfunktion)",
        home = "Hem",
        plugins = "Plugins",
        configuration = "Inställningar",
        back = "Tillbaka",
        save = "Spara inställningar",
        config_label = "Rapport‑ID som ska användas:",
        upgrade_status = "Uppgraderingsstatus",
        last_upgraded = "Plugin uppgraderades senast på detta system den",
        never_upgraded = "Plugin har aldrig uppgraderats."
    }
%]